version: "3"
services:
  web:
    build:
      dockerfile: ./php-apache/Dockerfile
      context: .
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html/

  db:
    build:
      dockerfile: ./mysql/Dockerfile
      context: .
    ports:
    - "3306:3306"
    volumes:
    - ./mysql/database/:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db
    depends_on:
      - db

#volumes:
#  mysql_data:
